framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'nikki@twist-club.com'
        headers:
            From: '[Futsal FM] <noresponderaestecorreo@example.com>'
